//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoRecord
    {
        public long ID { get; set; }
        public Nullable<long> FID { get; set; }
        public string DISTRICT { get; set; }
        public string BLOCK { get; set; }
        public string GP { get; set; }
        public string VILLAGE { get; set; }
        public string HABITATION { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public string PROPERTYID { get; set; }
        public string PROPERTYTYPE { get; set; }
        public Nullable<int> NUMBE_ROF_FLOORS { get; set; }
        public string CONSTRUCTIONTYPE { get; set; }
        public string CONSUMERNAME { get; set; }
        public string PHONENO { get; set; }
        public Nullable<int> FAMILYCOUNT { get; set; }
        public string WATERSUPPLYTYPE { get; set; }
        public Nullable<decimal> SUPPLY_IN_HOURS { get; set; }
        public Nullable<int> NUMBER_OF_CONNECTIONS { get; set; }
        public string REMARKS { get; set; }
        public string STATUS { get; set; }
        public string SURVEYOR_LOCATION { get; set; }
        public string USERNAME { get; set; }
        public string CONNECTIONSTATUS { get; set; }
        public string CONNECTIONPHOTO { get; set; }
        public Nullable<System.Guid> UPLOADEDBY { get; set; }
        public Nullable<System.DateTime> UPLOADEDON { get; set; }
        public Nullable<int> NumberOfRoom { get; set; }
        public string CONNECTIONTYPE { get; set; }
    }
}
