//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public string InvoiceNumber { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public Nullable<int> DeductionType { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public int CompanyId { get; set; }
        public System.Guid createdby { get; set; }
        public System.DateTime createdate { get; set; }
        public int InvoiceType { get; set; }
    }
}
