//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterLocation
    {
        public string District { get; set; }
        public string Block { get; set; }
        public string Gram_Panchayat { get; set; }
        public int Id { get; set; }
    }
}
