//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string ProductName { get; set; }
        public decimal ProductRate { get; set; }
        public int Quantity { get; set; }
        public int InvoiceId { get; set; }
        public int UnitType { get; set; }
        public bool IsTaxable { get; set; }
        public decimal TaxPercentage { get; set; }
    }
}
