//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KGS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductId { get; set; }
        public string ProductuCode { get; set; }
        public string ProductuName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<bool> IsTaxable { get; set; }
        public string ProductImage { get; set; }
        public decimal Rate { get; set; }
        public int Unit { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
    }
}
